import React from 'react';

const FACE_VALUE = 150;

export default function TaxReceiptModal({ game, nonprofit, seatCount, onClose }) {
  const total = (seatCount * FACE_VALUE).toFixed(2);
  const receiptId = `SMS-${game.id.slice(2)}-${nonprofit.id.slice(-4)}`.toUpperCase();
  const issued = new Date().toLocaleDateString(undefined, {
    year: 'numeric', month: 'long', day: 'numeric'
  });
  const gameDate = new Date(game.date + 'T12:00:00').toLocaleDateString(undefined, {
    weekday: 'long', month: 'long', day: 'numeric', year: 'numeric'
  });

  return (
    <div className="modal-overlay" onClick={onClose}>
      <div className="modal modal-wide" onClick={e => e.stopPropagation()}>
        <div className="modal-body receipt-print">
          <div className="receipt">
            <div className="receipt-header">
              <div>
                <div className="receipt-brand">⭐ ShareMySeats</div>
                <div className="receipt-sub">Powered by the Tampa Bay Rays Foundation</div>
              </div>
              <div className="receipt-id">
                <div>Receipt No.</div>
                <div className="receipt-id-num">{receiptId}</div>
              </div>
            </div>

            <h2 className="receipt-title">Charitable Donation Receipt</h2>
            <div className="receipt-issued">Issued {issued}</div>

            <div className="receipt-grid">
              <div>
                <div className="receipt-label">Donor</div>
                <div className="receipt-value">Season Ticket Holder</div>
                <div className="receipt-value-sub">Account #SMS-DEMO</div>
              </div>
              <div>
                <div className="receipt-label">Recipient Organization</div>
                <div className="receipt-value">{nonprofit.name}</div>
                <div className="receipt-value-sub">501(c)(3) verified</div>
              </div>
              <div>
                <div className="receipt-label">Game</div>
                <div className="receipt-value">{game.matchup}</div>
                <div className="receipt-value-sub">{gameDate} · {game.time}</div>
              </div>
              <div>
                <div className="receipt-label">Seats Donated</div>
                <div className="receipt-value">{seatCount} × Diamond Club</div>
                <div className="receipt-value-sub">Section 108, Row C</div>
              </div>
            </div>

            <div className="receipt-total-row">
              <div>
                <div className="receipt-label">Estimated Fair Market Value</div>
                <div className="receipt-value-sub">Per-seat face value × seats donated</div>
              </div>
              <div className="receipt-total">${total}</div>
            </div>

            <div className="receipt-fineprint">
              <p><strong>No goods or services were provided in exchange for this donation.</strong> The recipient organization is a registered 501(c)(3) tax-exempt entity. Please consult your tax advisor regarding the deductibility of this contribution.</p>
              <p>This receipt is generated by ShareMySeats on behalf of the donor. Retain for your tax records.</p>
            </div>

            <div className="receipt-sig">
              <div className="receipt-sig-line">_________________________</div>
              <div className="receipt-sig-name">Rays Foundation, Authorizing Officer</div>
            </div>
          </div>
        </div>

        <div className="modal-foot no-print">
          <button className="btn secondary" onClick={onClose}>Close</button>
          <button className="btn" onClick={() => window.print()}>📄 Print / Save as PDF</button>
        </div>
      </div>
    </div>
  );
}
